### ISSUE TITLE
printf replaced by puts

### ISSUE THREAD

**Issue by merces** [icyphox/asdf#2]
[Nice article](https://icyphox.sh/blog/python-for-re-1/), thanks for sharing it. 😉

By the way, in the article you say: 

> I’m not sure why it uses puts here? I might be missing something; perhaps printf calls puts.

That's actually a gcc "optimization": as your code does not use any formatting feature from _printf_ function (%d, %s, etc with runtime-dependant values) it can be replaced by the simpler _puts_, which is cheaper call.

You can disable that using the gcc **-fno-builtin-printf** option:

```
$ gcc -o chall.elf chall.c
$ nm chall.elf | grep -E puts
                 U puts@@GLIBC_2.2.5

$ gcc -fno-builtin-printf -o chall.elf chall.c
$ nm chall.elf | grep puts
$
```

Sorry about opening an issue here. There's no issue with your code/article but I found it the easiest way to contact you regarding this.

Ciao!

**Comment by icyphox** [comment]
Hey,
Thank you! I’d actually learnt about this a short while before publishing the post, just never got around to updating the text to say so. 

Thanks again, and no worries. You can always DM me on Twitter, though. :)

I’ll close this now.
